server:
  port: 8080

jwt:
  secret: JWT_SECRET
  expirationMs: 86400000

spring:
  application:
    name: api-gateway

  datasource:
    url: jdbc:mysql://localhost:3306/petinder_user_service
    username: tarkan
    password: 2553
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          globally_quoted_identifiers: true

zuul:
  ignoredServices: "*"
  routes:
    user-service:
      stripPrefix: true
      serviceId: PETFINDER-USER-SERVICE
      path: /user/**
      url: http://localhost:8081/v1/api
    animal-service:
      stripPrefix: true
      serviceId: PETFINDER-ANIMAL-SERVICE
      path: /animal/**
      url: http://localhost:8084/v1/api
    matching-service:
        stripPrefix: true
        serviceId: PETFINDER-MATCHING-SERVICE
        path: /match/**
        url: http://localhost:8085/v1/api

  strip-prefix: true
