server:
  port: 8080

jwt:
  secret: JWT_SECRET
  expirationMs: 86400000

spring:
  application:
    name: api-gateway

  datasource:
    url: jdbc:mysql://localhost:3306/petinder_user_service
    username: tarkan
    password: 2553
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          globally_quoted_identifiers: true


