spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/petinder_user_service
    username: tarkan
    password: 2553
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true
app.secretkey: tarkanyaman
app.expirationtime: 100000
